### ISSUE TITLE
term font?

### ISSUE THREAD

**Issue by brihadeesh** [m3atatarian/dots#1]
Hi I'd like to try out your version of `orp` but couldn't find it on your github. Any chance you're willing to share/add it to this repo?

**Comment by 4drift** [comment]
Apologies for the delayed response. I was almost just going to delete this github. I unfortunately didn't alter the name for orp so you can't have the original and this one installed unless you change it. I also made a bigger version of the font named twerp but the XLFD font string doesn't work so you have to set it using xft.

Otherwise I use them both and they work well. You can set it (if your terminal emulator supports it) via a command like this: `printf '\e]710;%s\007' "xft:twerp:pixelsize=12"` and change between orp and twerp on the fly. Should you fix that font string though I would happily use that version.

**Comment by 4drift** [comment]
Well. Now that I closed this I don't know if it'll show up to ya. But I recently got the XLFD font string working. `-misc-twerp-medium-r-normal--14-101-100-100-c-70-iso8859-1` works to set the font. IF the one uploaded doesn't work, if somebody can let me know and I will re-upload it.

**Comment by brihadeesh** [comment]
You really didn't have to take the trouble! It's also been a while since I've used bitmaps. Thanks regardless!
